### ISSUE TITLE
Serve.exe Problem

### ISSUE THREAD

**Issue by filt02** [CollapsedTeam/Collapsed-Engine-Cocos#1]
![server exe problem2](https://cloud.githubusercontent.com/assets/28469670/26006435/b8abecb8-3712-11e7-8cbf-771577f54de6.jpg)
![server exe problem2](https://cloud.githubusercontent.com/assets/28469670/26006358/7c509444-3712-11e7-8c7b-ba0a95d3069a.jpg)

Hello, I have some problems when running the program in server.exe

**Comment by ghost** [comment]
Should be fixed by 1116e6ece0a1a12f61eb4f20f96f24f0bcb8c88a

**Comment by filt02** [comment]
Thank you very much, I am 24 hours without sleeping trying to fix this error. This project is a beautiful work of art, come images and video. Congratulations

**Comment by filt02** [comment]
![problem 1](https://cloud.githubusercontent.com/assets/28469670/26008477/5353a744-371b-11e7-9396-778275f7c88b.png)
![problem 2](https://cloud.githubusercontent.com/assets/28469670/26008476/5353396c-371b-11e7-8bdd-ce5c6c4ec1a9.png)

Forgive the bother again. But I have these problems after having corrected mysql

**Comment by RMariowski** [comment]
I don't see any problem on the first screenshot.
On the second one, you are missing _Data_ folder.
 _Data_ folder must be in the same directory as .exe is.

**Comment by filt02** [comment]
Excuse me, could you give me information about this experience? And how could I have this file

**Comment by RMariowski** [comment]
[Click this link](https://github.com/CollapsedTeam/Collapsed-Engine/tree/Core/Server/Server)
Just go with the same path.

I wonder how you configured MySQL connection without notice that there is Config file in Data folder.

**Comment by filt02** [comment]
Answering about mysql: I configured the config.tpl.ini that already came with the files, I renamed it to config.ini and edited it. I am putting the serve.exe file in Collapsed-Engine-Core \ Server \ Server \ Data and the same problem and put it in Collapsed-Engine-Core \ Server \ Server and give equal problem Of the first image, do you need to bring all the files that contain Collapsed-Engine-Core \ Server \ Debug?

**Comment by RMariowski** [comment]
> and give equal problem Of the first image

To which screenshot do you refer? The first one in [this post](https://github.com/CollapsedTeam/Collapsed-Engine/issues/1#issuecomment-301131001) don't have any error/problem.
The structure of directory should look like this:
- Root directory
-- Data (with edited config.ini and Dialogues folder)
-- Server.exe
-- libmysql.dll

The rest files that are generated after compilation should not be required, if i remember it correctly.

Hope this helps.

**Comment by filt02** [comment]
forgive my friend bother and slowness of understanding. It all worked out. Thank you very much
